image: mjalas/javafx

build:
  script: "cd src && javac ProjetMode2017-N4/InterfaceTest.java"
  
test:
  script:
    - "cd tests && javac -cp hamcrest-core-1.3.jar:junit-4.12.jar:../src TestCommande.java"
    - "java -cp hamcrest-core-1.3.jar:junit-4.12.jar:../src/:. org.junit.runner.JUnitCore TestCommande"